# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: 성재호(Seong Jaeho)
title: Fullstack Developer
email: pok_gare@naver.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: sjh2428

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://avatars3.githubusercontent.com/u/26241585?s=460&u=9e4860590f599ef537f0f3294e206530135166f1&v=4
about_content: | # this will include new lines to allow paragraphs
  반갑습니다! 저는 풀스택 개발을 좋아하며 55:45로 백엔드를 조금 더 선호합니다.<br />
  주력 언어로는 <mark>ES6(Javascript)</mark>이며 최근에는 Java/Spring에 흥미를 느껴 학습하고 있습니다.

# Skills Section
# skill_title: Skills #(Use this to override about more section title)

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# Awards Section
# awards_title: Awards #(Use this to override about awards section title)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
